name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        
      - name: Run Tests
        run: vendor/bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to Production
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          echo "Setting up SSH known hosts"
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          
          echo "Deploying application..."
          rsync -avz --delete \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='storage/logs/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='.env' \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
          
          echo "Running post-deploy commands..."
          ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && \
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && \
            php artisan migrate --force && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache"
